spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
      location: "./tmpfiles"
  jpa:
    hibernate:
      ddl-auto:  create
    generate-ddl: true
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
server:
  port: 8090